server:
  port: 8080

spring:
  application:
    name: bot-telegram-assistant-client
  config:
    import: optional:file:.env[.properties]
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          model: ${GEMINI_MODEL}
    mcp:
      client:
        streamable-http:
          connections:
            products:
              url: ${MCP_SERVER_URI}

telegram:
  api:
    key: ${TELEGRAM_API_KEY}