server:
  port: 8089

spring:
  application:
    name: mcp-server
  ai:
    mcp:
      server:
        protocol: STREAMABLE
        name: products
        expose-mcp-client-tools: true
#  cache:
#    type: caffeine
